### PR TITLE
Update to up to date docker image based on openshift-integration2 branch

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Comment by slaskawi** [comment]
So did quite a bit of testing of this image. Here are my results:

- The token can be obtained without any problems:

```
./token                             
eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlUTR2R3hKenBWQ0V4dWhzajdiLWdDNmZ0Nm80cm9GcTNCUHpwbHRXU3NjIn0.eyJqdGkiOiI5MzAzMWI1MS1lM2M2LTQ0OWYtOGFiNC1lMmY2ZDgxNjBmNzIiLCJleHAiOjE1MzU1ODA2NDAsIm5iZiI6MCwiaWF0IjoxNTM1NTQ0NjQwLCJpc3MiOiJodHRwczovL2tleWNsb2FrLWRlZmF1bHQuMTcyLjE3LjAuMS5uaXAuaW8vYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoiYWRtaW4tY2xpIiwic3ViIjoiOGFmY2Q2ZTUtNTZkOC00OWU0LWFlNmMtZTdjNDVkODY0ZGRmIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYWRtaW4tY2xpIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiNTg3NzM5MTgtMjIwZS00ZGViLThlYjktODM3ODRhN2UzM2M4IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6W10sInJlc291cmNlX2FjY2VzcyI6e30sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.DL-JZUbRBl0lKoXud5xCDb_Hdr8f_mGiJJRRJJG7eB_rQJPTrBbsHH2haiPHIA-e6YBJwUcUSmQLdLwNKODVWoFPGHwiXh9BMfFXB9dKzMofH1100BlwjWhtxP2RzKj8WfdsAa3QinG4ND2GS0-DPw4SSemv5SwwDR0a3c30SRSiWHF0INPoGaY8dW1WBrScrS322uzw9yF5ub85JTzC7Cg4hyxxZF6ZR1oez3kofKFV5EBNcxiyuLtm6K16h0MfiK9GLN4i4RG1YlHa2QPF2RRAGiHIJYmZIfK89dVx1Q3ipAHMB6fG0OdaCMolCgUm202ERutkayv5VK8C-g3CtQ
```

- Querying OpenShift **doesn't** work:

```
oc get pods --token=`./token`
error: You must be logged in to the server (Unauthorized)
```

- Full API Server logs might be found [here](https://gist.github.com/slaskawi/7e01c24a3ec47b98e808b2c67aa217e6). There are a couple of errors but they don't seem to be related:

```
E0829 12:01:38.449141       1 reflector.go:205] github.com/openshift/origin/vendor/github.com/openshift/client-go/user/informers/externalversions/factory.go:58: Failed to list *v1.Group: the server could not find the requested resource (get groups.user.openshift.io)
E0829 12:01:38.499606       1 reflector.go:205] github.com/openshift/origin/pkg/quota/generated/informers/internalversion/factory.go:58: Failed to list *quota.ClusterResourceQuota: the server could not find the requested resource (get clusterresourcequotas.quota.openshift.io)
E0829 12:01:38.504236       1 reflector.go:205] github.com/openshift/origin/pkg/security/generated/informers/internalversion/factory.go:58: Failed to list *security.SecurityContextConstraints: the server could not find the requested resource (get securitycontextconstraints.security.openshift.io)
E0829 12:01:38.504278       1 reflector.go:205] github.com/openshift/origin/pkg/apps/generated/informers/internalversion/factory.go:58: Failed to list *apps.DeploymentConfig: the server could not find the requested resource (get deploymentconfigs.apps.openshift.io)
E0829 12:01:38.504350       1 reflector.go:205] github.com/openshift/origin/pkg/image/generated/informers/internalversion/factory.go:58: Failed to list *image.ImageStream: the server could not find the requested resource (get imagestreams.image.openshift.io)
```

- There are no errors in Keycloak logs
- Not sure if this is related (probably not) but Etcd pod emits a TLS warning:

```
WARNING: 2018/08/29 12:01:34 Failed to dial 0.0.0.0:4001: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"; please retry.
```

- The API Master container emits a weird, token-related error (but it doesn't stop it, it proceeds further):

```
E0829 12:14:01.727274       1 authentication.go:63] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, [x509: certificate signed by unknown authority, the server could not find the requested resource]]]
```

- I also invoked a tail on all the containers (see [this](https://stackoverflow.com/a/38308974/562699) how to do it) and invoked `oc get pods --token=$(./token)`. I stored full logs [here](https://gist.github.com/slaskawi/9993dcf8aa03987f7ab38dea717eda6f). The x509 error appears there several times, so my intuition tells me that this is why it doesn't work:

```
E0829 12:42:01.170246       1 authentication.go:63] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, [x509: certificate signed by unknown authority, the server could not find the requested resource]]]
```

However we haven't changed anything in this regard, have we? Interesting...

**Comment by slaskawi** [comment]
BTW, I haven't started integrating Mutual TLS into this. None of my scripts that play with keystores/truststores haven't kicked in yet.

**Comment by pedroigor** [comment]
@slaskawi, can you check logs for oc client ?

```shell
oc get --loglevel=8 pods --token=`./token`
```

As we discussed, I'm not using the keycloak server from that image but accessing a local server instance started using my IDE, so I can debug and implement things out.

I can try to setup a new env and try out the server deployed using that image in openshift.

**Comment by slaskawi** [comment]
I reverted my environment to the old image (`jboss/keycloak-openshift:nightly-openshift-integration`). The results are [here](https://gist.github.com/slaskawi/32cfc1396e3baca6ae79fb49014b2708). There are only Keycloak logs and OpenShift emits nothing. That's good!

@pedroigor Now let me get back to this PR and rerun the test.

**Comment by slaskawi** [comment]
@pedroigor After retesting this PR, here's what I got:

- `oc get pods --token=`./token` --loglevel 5` returns:

```
I0829 15:58:28.385995   11997 helpers.go:201] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}]
F0829 15:58:28.386052   11997 helpers.go:119] error: You must be logged in to the server (Unauthorized)
```

- I also got tail from all containers and issued the above command (oc get pods --token=`./token`). It seems I had some bad timing last time and grabbed redundant logs. Now OpenShift is silent, but the command still fails. Full logs are [here](https://gist.github.com/slaskawi/424a6d29c50c332abf8f39704aa2e715) but there's nothing interesting there.
- API Server logs still contain `E0829 13:58:25.571450       1 authentication.go:63] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, [x509: certificate signed by unknown authority, the server could not find the requested resource]]]`

**Comment by slaskawi** [comment]
@stianst That's my interpretation too. So here's what we have now:

- Yesterday I talked with @pedroigor about modifications to the ream that are required to get this working. I mentioned that all required changes need to be either pushed into this PR or there should be a follow up PR with all necessary changes. @pedroigor mentioned he'll be working on it on Friday (tomorrow).
- Since Token Review Endpoint requires the client to be authenticated, we need to setup Mutual TLS with x509 Client Authenticator. 
- The Mutual TLS work is currently blocked by the x509 error we see in the API Server logs. However, I might ignore this error for now and implement Mututal TLS. The downside is that I won't be able to verify if it works. 

My short plan for now:

- Revert to the old image and make sure the x509 is not there. 
- Remove my Mutual TLS code from the Docker image and check if the x509 is gone or not.
- Implement Mutual TLS (even though I can not test it out). 
- (possibly) Get some help on x509 cert issue on API Server.

**Comment by slaskawi** [comment]
> Revert to the old image and make sure the x509 error is not there.

That is correct, with the old image we do not have the x509 error.

**Comment by slaskawi** [comment]
> Remove my Mutual TLS code from the Docker image and check if the x509 error is gone or not.

I created an image `slaskawi/keycloak-no-mtls-2` (it's the same we are using in this PR but without executing my x509 script) and the x509 error is gone. Looking more into it...

**Comment by abstractj** [comment]
@stianst updated my PR with the changes you mentioned. Even though I get the same issue as @slaskawi (https://github.com/keycloak/openshift-integration/pull/14#issuecomment-416965923). Right now I'm investigating what's wrong in my setup.

**Pull request merged**
